language: c
matrix:
  include:
    - osx_image: xcode11.6
      os: osx
      env: OSFLAG="macos_catalina_amd64"
    - osx_image: xcode10.2
      os: osx
      env: OSFLAG="macos_mojave_amd64"
    - osx_image: xcode9.4
      os: osx
      env: OSFLAG="macos_high_sierra_amd64"
    - osx_image: xcode8.3
      os: osx
      env: OSFLAG="macos_sierra_amd64"
    - os: linux
      arch: amd64
      env: OSFLAG="linux_amd64"
script:
  - xcode-select --install
  - autoreconf -f -i -v
  - "./configure --without-libcrypto --without-fuse --without-ntfs-3g --disable-debug
    --disable-dependency-tracking --disable-silent-rules --enable-static --disable-shared"
  - make all -j
  - ./wimlib-imagex --version
  - export BIN_VERSION=$(./wimlib-imagex --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/' | head -1)
  - export BIN_NAME=wimlib-imagex-$BIN_VERSION-$OSFLAG
  - mv ./wimlib-imagex ./$BIN_NAME
deploy:
  provider: releases
  api_key:
    secure: lFXbPAc9crSTDvoFkhOM4yvkXVvJtnM9VQBXnYAdHy+iC0bzx1iC6qM+zmqSS//dEM9z/UvyfdD6gh4+A6rIG3bI2Xs42q9hIyBeVhBw+iZwSFXbeqiJAcG1xnyP6GlX4fwvP8I5x+ssLkHgn+uL9jVP5ZDJsTTuVlHQSuK9oAavmtirEBAHN3Y/JiFwNnxjTFnbI+q9CluadPH9JR2SuiAXUf9+AWENg06RhLGCd3cWhns+L8Cb6AyXrsACXISgEqkChaiRahYnUmiZLpBYbD8ih4Q+W/OFn3Blu5o9Jwj04plAIWglj6NttR1QBX3XyhisSo4aIc9k0twIlrlDaWagsPau5p6ZurpW3RD07yx3kXw+ZWNRGbcLLMR2SsdJJCjztQ6VIwNtbbwP7mQev0qagnNCzy2Ta8sTk2TOgA3/WtKcdeG5Jcset9C25yBE3wgp/Ja9CHNTe1AoiTGfzta5JlSqw81utWsHHvkkoWMjuD1bxc7kAVKS9KdGounxB1PJbTJUEni8SIYq3vVg2ajncT0B9ane2n8GYOY7bETBWjPDhurPqBBc+X/g5ms6VNEaURt2w6ypc529/tg4H2Ib6Jvz8A0hBT5E/lJP77A+cjZJ0YB65LeVaZ/uiq04OgJutKIXZLE6aKO5q4yjveUKhAR8ZqE/8oMh5r+ZJL4=
  file: $BIN_NAME
  on:
    repo: esa-app/wimlib-buildbot
    all_branches: true
    tags: true
  skip_cleanup: "true"
