language: c
matrix:
  include:
    - osx_image: xcode11.6
      os: osx
      env: OSFLAG="macos_catalina_amd64"
    - osx_image: xcode10.3
      os: osx
      env: OSFLAG="macos_mojave_amd64"
    - osx_image: xcode9.4
      os: osx
      env: OSFLAG="macos_high_sierra_amd64"
    - osx_image: xcode8.3
      os: osx
      env: OSFLAG="macos_sierra_amd64"
    - os: linux
      arch: amd64
      env: OSFLAG="linux_amd64"
script:
  - bash libxml2_patch.sh
  - autoreconf -f -i -v
  - "./configure --without-libcrypto --without-fuse --without-ntfs-3g --disable-debug
    --disable-dependency-tracking --disable-silent-rules --enable-static --disable-shared"
  - make all
  - ./wimlib-imagex --version
  - export BIN_VERSION=$(./wimlib-imagex --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/' | head -1)
  - export BIN_NAME=wimlib-imagex-$BIN_VERSION-$OSFLAG
  - mv ./wimlib-imagex ./$BIN_NAME
deploy:
  provider: releases
  api_key:
    secure: Y/3fk41rFw/cGz3tOXvT1lUKSsv35HXhCADBmiuo3Bl4lkwa+xByk4TFX4ytp7+yK+3mY+cpi9cRlZqL5ouLelMBJsRLLwXdq5YlRSWngShvslV1qxwaEkTYH+LoM+ZyR7iNbljZBFyBVcR3bJluPXvkiG3142RUPZTnzUXnuefAwtYn6ZGQYaCQxkWAeOgn63D7/00xYpRNGdoDo630Jooe374Z3wcp5KeM+4CGuWZhg2AQn3TQb8VOiGk81PSFt5pY1lcNoqMnUc18tpbvs6T87sCwfN/qebFT7v6kyArsDcEc6AoUPCkEdMe611CGqeeKfw032IVQTR2dLYCgXuJsSJIv+3nFVvIKGIkC8FFCFVsZoIrP7QSiAcrWVKuoFdiypVSbBivAS1y6WwmoAXGYw7zQgpehE6SgNOB2/FCfW4K9ciLCMrB3xm5yp5Wde0zymySUuZ4eitJvO/SSmf3QunkUajBFQNZwm0o8hwHcFCocfrU8AvvROkojP2NksJwVBMZZ6DIMkHtpxRCUu5zUFv4dzkO2OjX+20u8DeD5m2Gr/Wq09TQs/7R1ECxb9SeiXkfTDuNGN8Z9i3D6TCdQn4o6DxzdK/tcRRQQDi3RZyx5AQ1z4YdN/np+lD/EWcetEqfAQL5HlnzsTXTw3KNSi98P9IXEbvc3J3RIpvs=
  file: $BIN_NAME
  on:
    repo: esa-app/wimlib-buildbot
    all_branches: true
    tags: true
  skip_cleanup: "true"
